version: '3'
services:
    nginx:
        env_file:
            - ./config.env
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt/"
        ports:
            - 80:80
            - 443: 443
        networks:
            - stockprice
        
    app:
        image: stockprice_app:latest
        container_name: app
        expose:
            - "5000"
        networks: 
            - stockprice
networks:
    stockprice:
    